#!/bin/bash

# --- Color Definitions ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# --- Helper Functions ---
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo -e "${CYAN}${BOLD}========================================="
echo -e " KoelOS Advanced Build Engine (VirtualBox)"
echo -e "=========================================${NC}"

# [0] Pre-flight Check
log_info "Running pre-flight checks..."
[ ! -f boot.asm ] && log_error "boot.asm missing!"
[ ! -f kernel.asm ] && log_error "kernel.asm missing!"
mkdir -p drivers apps

# [1] Cleanup
log_info "Cleaning workspace..."
rm -f boot.bin kernel.bin os.img os_padded.img os.vdi generated_apps.asm build.log

# [2] Component Discovery
log_info "Generating component manifest..."
GEN_FILE="generated_apps.asm"
echo "; --- Auto-generated by Build Script ---" > $GEN_FILE

echo -e "\n; --- System Drivers ---" >> $GEN_FILE
DRV_COUNT=0
for f in drivers/*.asm; do
    if [ -e "$f" ]; then
        # SKIP LIST: These are manually included in 00_net_stack.asm
        [[ "$f" == "drivers/arp_handle.asm" ]] && continue
        [[ "$f" == "drivers/dns.asm" ]] && continue
        [[ "$f" == "drivers/tcp.asm" ]] && continue
        [[ "$f" == "drivers/http.asm" ]] && continue

        echo "%include \"$f\"" >> $GEN_FILE
        ((DRV_COUNT++))
    fi
done

echo -e "\ncommand_table:" >> $GEN_FILE
APP_COUNT=0
for f in apps/*.asm; do
    if [ -e "$f" ]; then
        APP_NAME=$(basename "$f" .asm)
        echo "    dq cmd_$APP_NAME, do_$APP_NAME" >> $GEN_FILE
        ((APP_COUNT++))
    fi
done
echo "    dq 0, 0" >> $GEN_FILE

echo -e "\n; --- User Applications ---" >> $GEN_FILE
for f in apps/*.asm; do
    if [ -e "$f" ]; then
        echo "%include \"$f\"" >> $GEN_FILE
    fi
done

log_success "Manifest created with $DRV_COUNT drivers and $APP_COUNT apps."

# [3] Compilation
log_info "Compiling Bootloader..."
if ! nasm -f bin boot.asm -o boot.bin 2>build.log; then
    log_error "Bootloader failed!\n$(cat build.log)"
fi

log_info "Compiling Kernel..."
# Note: Added -w-label-redef-late to help with multi-pass label shifts
if ! nasm -f bin kernel.asm -o kernel.bin -w-label-redef-late 2>build.log; then
    echo -e "${RED}${BOLD}FATAL: Kernel/App Error Detected!${NC}"
    grep "error" build.log | sed "s/^/  /"
    exit 1
fi

# [4] Finalization
log_info "Stitching system image..."
cat boot.bin kernel.bin > os.img

dd if=os.img of=os_padded.img bs=512 conv=sync 2>/dev/null
IMG_SIZE=$(wc -c < os_padded.img)
log_success "Image 'os.img' created and padded ($IMG_SIZE bytes)."

# [5] VirtualBox Deployment
VM_NAME="KoelOS"
VDI_FILE="$(pwd)/os.vdi"

log_info "Preparing VirtualBox Drive..."
VBoxManage storageattach "$VM_NAME" --storagectl "IDE Controller" --port 0 --device 0 --type hdd --medium none >/dev/null 2>&1
VBoxManage closemedium disk "$VDI_FILE" --delete >/dev/null 2>&1
VBoxManage convertfromraw os_padded.img "$VDI_FILE" --format VDI >/dev/null 2>&1

if ! VBoxManage showvminfo "$VM_NAME" >/dev/null 2>&1; then
    log_info "First run detected! Creating VM '$VM_NAME'..."
    VBoxManage createvm --name "$VM_NAME" --ostype "Other_64" --register >/dev/null
    VBoxManage modifyvm "$VM_NAME" --memory 512 --vram 16 --boot1 disk
    VBoxManage modifyvm "$VM_NAME" --nic1 nat --nictype1 82540EM --nicpromisc1 allow-all --macaddress1 525400123456
    VBoxManage storagectl "$VM_NAME" --name "IDE Controller" --add ide
fi

log_info "Attaching drive to VM..."
VBoxManage storageattach "$VM_NAME" --storagectl "IDE Controller" --port 0 --device 0 --type hdd --medium "$VDI_FILE"

echo -e "\n${GREEN}${BOLD}BUILD COMPLETE! Launching VirtualBox...${NC}\n"
VBoxManage startvm "$VM_NAME" --type gui