#!/bin/bash
set -euo pipefail

# --- Color Definitions ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# --- Helper Functions ---
log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
BUILD_DIR="$ROOT_DIR/build"
DIST_DIR="$ROOT_DIR/dist/metal"
GEN_FILE="$BUILD_DIR/generated_apps.asm"
BUILD_LOG="$BUILD_DIR/build.log"
BOOT_BIN="$DIST_DIR/boot.bin"
KERNEL_BIN="$DIST_DIR/kernel.bin"
METAL_IMG="$DIST_DIR/koelOS-metal.img"
IMAGE_MB=64
MAX_KERNEL_SECTORS=127

echo -e "${CYAN}${BOLD}========================================="
echo -e " KoelOS Advanced Build Engine (Metal)"
echo -e "=========================================${NC}"

# Make globbing safe if folders are empty
shopt -s nullglob

# [0] Pre-flight Check
log_info "Running pre-flight checks..."
[ ! -f "$ROOT_DIR/boot.asm" ] && log_error "boot.asm missing!"
[ ! -f "$ROOT_DIR/kernel.asm" ] && log_error "kernel.asm missing!"
mkdir -p "$BUILD_DIR" "$DIST_DIR"

# [1] Cleanup
log_info "Cleaning build output..."
rm -f "$GEN_FILE" "$BUILD_LOG" "$BOOT_BIN" "$KERNEL_BIN" "$METAL_IMG"

# [2] Component Discovery
log_info "Generating component manifest..."
echo "; --- Auto-generated by Build Script ---" > "$GEN_FILE"

echo -e "\n; --- System Drivers ---" >> "$GEN_FILE"
DRV_COUNT=0
for f in "$ROOT_DIR"/drivers/*.asm; do
    # SKIP LIST: These are manually included elsewhere
    NAME="$(basename "$f")"
    [[ "$NAME" == "arp_handle.asm" ]] && continue
    [[ "$NAME" == "dns.asm" ]] && continue
    [[ "$NAME" == "tcp.asm" ]] && continue
    [[ "$NAME" == "http.asm" ]] && continue

    echo "%include \"drivers/$NAME\"" >> "$GEN_FILE"
    ((DRV_COUNT++))
done

echo -e "\ncommand_table:" >> "$GEN_FILE"
APP_COUNT=0
for f in "$ROOT_DIR"/apps/*.asm; do
    APP_NAME=$(basename "$f" .asm)
    echo "    dq cmd_$APP_NAME, do_$APP_NAME" >> "$GEN_FILE"
    ((APP_COUNT++))
done
echo "    dq 0, 0" >> "$GEN_FILE"

echo -e "\n; --- User Applications ---" >> "$GEN_FILE"
for f in "$ROOT_DIR"/apps/*.asm; do
    NAME="$(basename "$f")"
    echo "%include \"apps/$NAME\"" >> "$GEN_FILE"
done

log_success "Manifest created with $DRV_COUNT drivers and $APP_COUNT apps."

# [3] Compilation
log_info "Compiling Kernel..."
if ! nasm -f bin "$ROOT_DIR/kernel.asm" -o "$KERNEL_BIN" -w-label-redef-late 2>"$BUILD_LOG"; then
    echo -e "${RED}${BOLD}FATAL: Kernel/App Error Detected!${NC}"
    grep -i "error" "$BUILD_LOG" | sed "s/^/  /" || true
    exit 1
fi

KERNEL_SIZE=$(wc -c < "$KERNEL_BIN")
KERNEL_SECTORS=$(((KERNEL_SIZE + 511) / 512))
if [ "$KERNEL_SECTORS" -le 0 ]; then
    log_error "kernel.bin is empty!"
fi
if [ "$KERNEL_SECTORS" -gt "$MAX_KERNEL_SECTORS" ]; then
    log_error "kernel.bin needs $KERNEL_SECTORS sectors. Increase the boot load window before growing past $MAX_KERNEL_SECTORS sectors."
fi

log_info "Compiling Bootloader for $KERNEL_SECTORS kernel sectors..."
if ! nasm -f bin "$ROOT_DIR/boot.asm" -o "$BOOT_BIN" -d KERNEL_SECTORS="$KERNEL_SECTORS" 2>"$BUILD_LOG"; then
    log_error "Bootloader failed!"
fi

# [4] Create BIOS hard-disk image
log_info "Creating BIOS hard-disk image..."
dd if=/dev/zero of="$METAL_IMG" bs=1m count="$IMAGE_MB" status=none

# Boot sector must be exactly 512 bytes
BOOT_SIZE=$(wc -c < "$BOOT_BIN")
if [ "$BOOT_SIZE" -ne 512 ]; then
    log_error "boot.bin must be exactly 512 bytes (currently $BOOT_SIZE)"
fi

# Write bootloader to LBA 0 and kernel to LBA 1+
dd if="$BOOT_BIN" of="$METAL_IMG" conv=notrunc bs=512 count=1 status=none
dd if="$KERNEL_BIN" of="$METAL_IMG" conv=notrunc bs=512 seek=1 status=none

IMG_SIZE=$(wc -c < "$METAL_IMG")
log_success "Metal image created: $METAL_IMG ($IMG_SIZE bytes)"

echo -e "\n${GREEN}${BOLD}BUILD COMPLETE!${NC}"
echo "Kernel size:  $KERNEL_SIZE bytes ($KERNEL_SECTORS sectors)"
echo "Bootloader:   $BOOT_BIN"
echo "Kernel:       $KERNEL_BIN"
echo "Disk image:   $METAL_IMG"
