#!/bin/bash
set -euo pipefail

# --- Color Definitions ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# --- Helper Functions ---
log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

echo -e "${CYAN}${BOLD}========================================="
echo -e " KoelOS Advanced Build Engine"
echo -e "=========================================${NC}"

# Make globbing safe if folders are empty
shopt -s nullglob

# [0] Pre-flight Check
log_info "Running pre-flight checks..."
[ ! -f boot.asm ] && log_error "boot.asm missing!"
[ ! -f kernel.asm ] && log_error "kernel.asm missing!"
mkdir -p drivers apps

# [1] Cleanup
log_info "Cleaning workspace..."
rm -f boot.bin kernel.bin koelOS.img generated_apps.asm build.log

# [2] Component Discovery
log_info "Generating component manifest..."
GEN_FILE="generated_apps.asm"
echo "; --- Auto-generated by Build Script ---" > "$GEN_FILE"

echo -e "\n; --- System Drivers ---" >> "$GEN_FILE"
DRV_COUNT=0
for f in drivers/*.asm; do
    # SKIP LIST: These are manually included elsewhere
    [[ "$f" == "drivers/arp_handle.asm" ]] && continue
    [[ "$f" == "drivers/dns.asm" ]] && continue
    [[ "$f" == "drivers/tcp.asm" ]] && continue
    [[ "$f" == "drivers/http.asm" ]] && continue

    echo "%include \"$f\"" >> "$GEN_FILE"
    ((DRV_COUNT++))
done

echo -e "\ncommand_table:" >> "$GEN_FILE"
APP_COUNT=0
for f in apps/*.asm; do
    APP_NAME=$(basename "$f" .asm)
    echo "    dq cmd_$APP_NAME, do_$APP_NAME" >> "$GEN_FILE"
    ((APP_COUNT++))
done
echo "    dq 0, 0" >> "$GEN_FILE"

echo -e "\n; --- User Applications ---" >> "$GEN_FILE"
for f in apps/*.asm; do
    echo "%include \"$f\"" >> "$GEN_FILE"
done

log_success "Manifest created with $DRV_COUNT drivers and $APP_COUNT apps."

# [3] Compilation
log_info "Compiling Bootloader..."
if ! nasm -f bin boot.asm -o boot.bin 2>build.log; then
    log_error "Bootloader failed!"
fi

log_info "Compiling Kernel..."
if ! nasm -f bin kernel.asm -o kernel.bin -w-label-redef-late 2>build.log; then
    echo -e "${RED}${BOLD}FATAL: Kernel/App Error Detected!${NC}"
    grep -i "error" build.log | sed "s/^/  /" || true
    exit 1
fi

# [4] Create 1.44MB floppy image
log_info "Creating 1.44MB floppy image..."
IMG="koelOS.img"

# 1.44MB = 2880 sectors * 512 bytes
dd if=/dev/zero of="$IMG" bs=512 count=2880 status=none

# Boot sector must be exactly 512 bytes
BOOT_SIZE=$(wc -c < boot.bin)
if [ "$BOOT_SIZE" -ne 512 ]; then
    log_error "boot.bin must be exactly 512 bytes (currently $BOOT_SIZE)"
fi

# Write bootloader to sector 0
dd if=boot.bin of="$IMG" conv=notrunc bs=512 count=1 status=none

# Write kernel starting at sector 1 (LBA 1 = second 512-byte sector)
dd if=kernel.bin of="$IMG" conv=notrunc bs=512 seek=1 status=none

IMG_SIZE=$(wc -c < "$IMG")
log_success "Valid floppy image created: $IMG ($IMG_SIZE bytes)"

echo -e "\n${GREEN}${BOLD}BUILD COMPLETE!${NC}"
echo "Output image: $IMG"