; --- Auto-generated by Build Script ---

; --- System Drivers ---
%include "drivers/00_net_stack.asm"
%include "drivers/checksum.asm"
%include "drivers/e1000_init.asm"
%include "drivers/e1000_rx.asm"
%include "drivers/e1000_tx.asm"
%include "drivers/net_utils.asm"
%include "drivers/pci_find.asm"
%include "drivers/print_dec.asm"
%include "drivers/print_hex.asm"
%include "drivers/string.asm"
%include "drivers/vga_cursor.asm"
%include "drivers/vga_scroll.asm"
%include "drivers/vga_text.asm"

command_table:
    dq cmd_announce, do_announce
    dq cmd_colors, do_colors
    dq cmd_dhcp, do_dhcp
    dq cmd_diag, do_diag
    dq cmd_dns, do_dns
    dq cmd_fetch, do_fetch
    dq cmd_help, do_help
    dq cmd_ifconfig, do_ifconfig
    dq cmd_ip, do_ip
    dq cmd_listen, do_listen
    dq cmd_netinit, do_netinit
    dq cmd_ping, do_ping
    dq cmd_ver, do_ver
    dq 0, 0

; --- User Applications ---
%include "apps/announce.asm"
%include "apps/colors.asm"
%include "apps/dhcp.asm"
%include "apps/diag.asm"
%include "apps/dns.asm"
%include "apps/fetch.asm"
%include "apps/help.asm"
%include "apps/ifconfig.asm"
%include "apps/ip.asm"
%include "apps/listen.asm"
%include "apps/netinit.asm"
%include "apps/ping.asm"
%include "apps/ver.asm"
